### ISSUE TITLE
Реализация метода получения статистики

### ISSUE THREAD

**Issue by ii-reviewer** [Alohanastacia/Masterskaya_Project_GO_1#24]
Реализовать метод для получения статистики жалоб с фильтрацией по разным параметрам.
Написать unit-тесты для логики статистики.

```
  /reports/statistics:
    get:
      summary: Получение статистики жалоб
      description: Получить статистику жалоб за день, неделю или месяц, с возможностью фильтрации по дате, статусам и категориям.
      security:
        - bearerAuth: []
```

TODO:
1. новый метод
2. SQL запросы и новый сервисный слой

DOD:
1. метод работает
